<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputSearch</name>
   <tag></tag>
   <elementGuidId>9b7d95e5-5cbe-46f5-a7ad-d408879c21d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='m']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@data-testid = 'searchInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.header-alz-112.default-placeholder.header-alz-113</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72d93686-c611-40d0-b509-e06cd0b574df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-alz-112 default-placeholder header-alz-113</value>
      <webElementGuid>694d36b4-1164-4480-9ae5-a2663e7951f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Co hledáte? Např. kabel AlzaPower...</value>
      <webElementGuid>24c2b506-98de-4ca8-a1bd-350e5e669967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>86294f53-35f5-411d-9098-e97870294e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>searchInput</value>
      <webElementGuid>42de5c3a-d60b-4038-ade6-3609f68fd8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f65f5372-dee0-466c-8ea2-1ae38fb8b28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>m</value>
      <webElementGuid>fcae170e-1e27-4828-9018-a7cdf5bf39d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/div[1]/div[@class=&quot;component header&quot;]/div[@class=&quot;MuiScopedCssBaseline-root header-148hyp&quot;]/div[@class=&quot;header-alz-1&quot;]/div[@class=&quot;header-alz-2&quot;]/header[@class=&quot;header-alz-3 header-alz-4 header-alz-8&quot;]/div[@class=&quot;header-alz-6&quot;]/div[@class=&quot;header-alz-94 header-alz-103 showBackdrop&quot;]/div[@class=&quot;header-alz-104&quot;]/div[@class=&quot;header-alz-108 header-alz-105 default-placeholder&quot;]/input[@class=&quot;header-alz-112 default-placeholder header-alz-113&quot;]</value>
      <webElementGuid>c656593a-e086-45d4-9daa-aff17127feb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='m']</value>
      <webElementGuid>2c96b906-2253-4015-a370-64ebf89daea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div/div/div/div/div/header/div[5]/div/div/div/input</value>
      <webElementGuid>08393c7a-0819-4f04-be43-af9b0769fd93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>caf8925e-649f-40a4-9c9e-ffc4bc520980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Co hledáte? Např. kabel AlzaPower...' and @type = 'text']</value>
      <webElementGuid>032001f0-ff7e-4e13-8cd8-0c3df1e63935</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
