<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AcceptCookieButton</name>
   <tag></tag>
   <elementGuidId>aead2e91-0ec6-4444-be97-686b0624a225</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btnx.cookies-info__button.js-cookies-info-accept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='boxes']/div[contains(@class,'canBuy inStockAvailability')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = 'javascript:Alza.Web.Cookies.acceptAllCookies();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3fbad3fb-446d-46cf-8db6-ee7603884135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnx cookies-info__button js-cookies-info-accept</value>
      <webElementGuid>e74bedad-fa32-463e-ae76-be39a10fb1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-api-url</name>
      <type>Main</type>
      <value>https://webapi.alza.cz/api/visitors/8097483836/v1/activities</value>
      <webElementGuid>7c684ea9-eeea-4634-8484-19d6292b1bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-type-value</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>0c0fb9f5-76dc-4a7c-9924-d14758f8507f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-id-value</name>
      <type>Main</type>
      <value>1023</value>
      <webElementGuid>5a36ced1-4ee1-4f32-8796-873c85266efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-speed-curve</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ab02a739-0517-4fc8-97fb-f87d44a187d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:Alza.Web.Cookies.acceptAllCookies();</value>
      <webElementGuid>80f6eec6-fb11-4fe8-8b5e-138b7e820484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rozumím</value>
      <webElementGuid>842b6ff3-e570-49cb-878b-94a503e17fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rootHtml&quot;)/body[@class=&quot;default alza-cz alza&quot;]/div[@class=&quot;js-cookies-info cookies-info&quot;]/div[@class=&quot;cookies-info__container&quot;]/div[@class=&quot;cookies-info__inner&quot;]/div[@class=&quot;cookies-info__buttons&quot;]/a[@class=&quot;btnx cookies-info__button js-cookies-info-accept&quot;]</value>
      <webElementGuid>66396674-bf82-493e-8559-3b8b9de1a7f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='rootHtml']/body/div[7]/div/div/div[2]/a</value>
      <webElementGuid>14f00d4a-87e6-4077-83e8-1d87d6aeea07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Rozumím')]</value>
      <webElementGuid>625062d8-5a67-4364-a64c-989adc924923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podmínkách ochrany os. údajů'])[1]/following::a[1]</value>
      <webElementGuid>041a923d-774e-4546-bce0-ad12747d7d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Více o Vašich právech'])[1]/following::a[2]</value>
      <webElementGuid>b87bb63d-9f88-44a3-ac50-c27a514a507f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podrobné nastavení'])[1]/preceding::a[1]</value>
      <webElementGuid>a2619e4d-cbe0-4b43-84d5-02cc6cffaee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odmítnout vše'])[1]/preceding::a[2]</value>
      <webElementGuid>521d57d8-196f-4090-baac-f662e3e8df0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rozumím']/parent::*</value>
      <webElementGuid>ce58baab-72c0-4cbb-932b-ec315fa6d37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:Alza.Web.Cookies.acceptAllCookies();')]</value>
      <webElementGuid>b6937a41-39b5-491d-961d-824c42a17aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/a</value>
      <webElementGuid>3ca5a8e1-98de-4d9b-90c9-b84f1c2a554a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:Alza.Web.Cookies.acceptAllCookies();' and (text() = 'Rozumím' or . = 'Rozumím')]</value>
      <webElementGuid>27b40f5c-dde0-4e66-940b-f43818117bf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
