<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AcceptCookieButton</name>
   <tag></tag>
   <elementGuidId>aead2e91-0ec6-4444-be97-686b0624a225</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='rootHtml']/body/div[7]/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'btnx cookies-info__button js-cookies-info-accept']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btnx.cookies-info__button.js-cookies-info-accept</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a13b5965-a356-4e3f-9301-5cc094d98f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnx cookies-info__button js-cookies-info-accept</value>
      <webElementGuid>ef7b92a2-d328-49cf-8017-0d39331363c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-api-url</name>
      <type>Main</type>
      <value>https://webapi.alza.cz/api/visitors/8097483836/v1/activities</value>
      <webElementGuid>197eaeaf-fd63-4d28-a5f9-eb2f824022a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-type-value</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>2fd56489-d7db-426c-b400-512c28adcd17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-id-value</name>
      <type>Main</type>
      <value>1023</value>
      <webElementGuid>d4d527a0-8740-4351-9c5a-71cf6db75e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-speed-curve</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>78a75620-354a-4472-9741-c00b342ee4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:Alza.Web.Cookies.acceptAllCookies();</value>
      <webElementGuid>49036f6b-55c9-4ffd-9f94-d7d8c2fb6150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rozumím</value>
      <webElementGuid>61522e03-9f7b-4fcf-a2f9-730d2ef08b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rootHtml&quot;)/body[@class=&quot;default alza-cz alza&quot;]/div[@class=&quot;js-cookies-info cookies-info&quot;]/div[@class=&quot;cookies-info__container&quot;]/div[@class=&quot;cookies-info__inner&quot;]/div[@class=&quot;cookies-info__buttons&quot;]/a[@class=&quot;btnx cookies-info__button js-cookies-info-accept&quot;]</value>
      <webElementGuid>a0f1118f-2532-45e4-a52a-9325c3fd133d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='rootHtml']/body/div[7]/div/div/div[2]/a</value>
      <webElementGuid>b4fa51f4-6059-49d0-af71-2d0c5c055ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Rozumím')]</value>
      <webElementGuid>aa2d01a2-fdbb-40b8-8aab-2048cd989912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podmínkách ochrany os. údajů'])[1]/following::a[1]</value>
      <webElementGuid>20369e5e-9ec8-4d87-80d4-04bc1df1fcf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Více o Vašich právech'])[1]/following::a[2]</value>
      <webElementGuid>090f3d99-3a97-442f-b146-992dc5497922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podrobné nastavení'])[1]/preceding::a[1]</value>
      <webElementGuid>77d430a7-fd16-4080-a8ba-bfbde67ff80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odmítnout vše'])[1]/preceding::a[2]</value>
      <webElementGuid>d0ced982-4454-4d21-8791-8249b98622f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rozumím']/parent::*</value>
      <webElementGuid>a5749df6-3d80-442b-b9ea-0338e9e80437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:Alza.Web.Cookies.acceptAllCookies();')]</value>
      <webElementGuid>44ba4d89-f3ee-4ea4-9566-42c87509bc85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/a</value>
      <webElementGuid>996eb1a7-1250-4df3-8865-10e43330addc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:Alza.Web.Cookies.acceptAllCookies();' and (text() = 'Rozumím' or . = 'Rozumím')]</value>
      <webElementGuid>5da341a4-f6f7-482d-9231-d6ab1af3a41d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
